### ISSUE TITLE
Outlined icons not rounded

### ISSUE THREAD

**Issue by FelixMittermeier** [ez-connect/flutter-ionicons#1]
Hi and thank you for the easy-to-use library.
Unfortunatly the outlined icons are not rounded as the originals on the website.
Take the "help-circle-outline" as an example:

Should be:
<img width="196" alt="Bildschirmfoto 2020-09-09 um 14 59 59" src="https://user-images.githubusercontent.com/33794642/92601892-a6cdf180-f2ad-11ea-875c-a29dfdb62489.png">

Is: 
![marked_icon](https://user-images.githubusercontent.com/33794642/92602987-198b9c80-f2af-11ea-92e9-4381144b74fe.png)

Maybe there is something you can do about that? Would be really great 👍 

Greetings

**Comment by vnhdx** [comment]
I use an older version - **v5.0.1** - which used by [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons). I will upgrade it if there is a new **TTF** version available.

Thank you

**Comment by FelixMittermeier** [comment]
Unfortunately it looks like the react-native-vector-icons library is not so good maintened. Perhaps one could download the icons from the ionicons website and create the updated ttf yourself with software like https://glyphter.com/.
It just looks much nicer with the softly rounded edges on the outlined icons.

**Comment by vnhdx** [comment]
Fixed in `v0.1.0`
