### ISSUE TITLE
Icons not working in web

### ISSUE THREAD

**Issue by keanallen** [ez-connect/flutter-ionicons#14]
Hi after switching from `desktop` to `web`, all my Icons are not working anymore.

`ionicons: v0.2.1`

Icons looks like this: `[X]`

![image](https://user-images.githubusercontent.com/45480782/185272712-cca9decf-6718-4600-a8b6-c920a232947f.png)

**Comment by vnhdx** [comment]
Hi @keanallen, if you use `CanvasKit`, it seems custom fonts are not supported. You can use `HTML` to allow the fonts.

```bash
flutter run -d web-server -web-renderer html
flutter build web --release -web-renderer html
```

For example https://github.com/ez-connect/flutter-ionicons/blob/50014c2451d003d9912f1e38c8e659c4575dbbe0/example/Makefile#L13

**Comment by Ahmadre** [comment]
> Hi @keanallen, if you use `CanvasKit`, it seems custom fonts are not supported. You can use `HTML` to allow the fonts.
> 
> ```shell
> flutter run -d web-server -web-renderer html
> flutter build web --release -web-renderer html
> ```
> 
> For example
> 
> https://github.com/ez-connect/flutter-ionicons/blob/50014c2451d003d9912f1e38c8e659c4575dbbe0/example/Makefile#L13

This is NOT a solution! HTML Renderer is going to be deleted: https://github.com/flutter/flutter/issues/145954
