### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by k4rm3l0** [ez-connect/flutter-ionicons#4]
Hello there,
I'm on a Flutter Web project and i try to add this library.

Unfortunally i see this icon with every icon name:
ex. this is Icon(Ionicons.add)
![Screenshot 2021-01-29 at 15 28 21](https://user-images.githubusercontent.com/4647229/106287483-218cae80-6247-11eb-96fa-dc2f6d8c0f1d.png)

My Flutter Doctor is:

<img width="632" alt="Screenshot 2021-01-29 at 15 31 22" src="https://user-images.githubusercontent.com/4647229/106287698-67e20d80-6247-11eb-87cd-6fcb7d61eb34.png">

**Comment by vnhdx** [comment]
Hi! I have tried with a fresh project, but can't reproduce your issue

1. Create a new project

```sh
flutter create app
```

2. Add to `pubspec.yaml`

```yml
ionicons: ^0.1.1
```

3. Add some icons in `main.dart`

```dart
...
Icon(Ionicons.add),
Icon(Ionicons.add_outline),
Icon(Ionicons.balloon),
Icon(Ionicons.balloon_outline),
Icon(Ionicons.logo_apple),
Icon(Ionicons.logo_microsoft),
...
```
![image](https://user-images.githubusercontent.com/6523928/106412217-c1ca1980-6479-11eb-90b1-849e7255c1b7.png)
