### ISSUE TITLE
Youtube Logo desn't render correctly

### ISSUE THREAD

**Issue by GonDragon** [ez-connect/flutter-ionicons#7]
The logo it's just a rounded square, without the Play symbol.

How it's used:
`Icon(
            Ionicons.logo_youtube,
            color: Theme.of(context).buttonColor,
          )`

How it looks (Screen Capture Attached).
![IMG_20210528_110033](https://user-images.githubusercontent.com/7538144/119995779-536b1300-bfa4-11eb-98ba-42e9a89f89ba.jpg)

**Comment by reafeichtinger** [comment]
I also noticed that a few items do not render correctly. Especially outlined icons sometimes get filled when they are not supposed to.

![image](https://user-images.githubusercontent.com/80401865/122665030-2c6bbf80-d1a5-11eb-84d1-5c5b94efb5dd.png)

For the left icon I have used `Ionicons.bluetooth_outline`
For the right icon I have used `Ionicons.share_social_outline`

**Comment by Goolpe** [comment]
Same issue with 
options_outline,
ellipsis_vertical_outline,
ellipsis_horizontal_outline,
pin_outline,

**Comment by reg-is** [comment]
Same problem for the following icons. Parts get filled, that should not:
chatbox_ellipses
chatbubble_ellipses
settings
